# Generated by Django 4.1.1 on 2022-10-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='last_visit',
            new_name='last_request',
        ),
    ]
